In [1]:
import numpy as np
np.__version__


'2.0.0'

In [2]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



Create An Array

In [4]:
arr1 = np.arange(0,100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
np.arange? # This is to know about function

SyntaxError: invalid syntax (943155049.py, line 1)

In [7]:
arr3= np.arange(0,100,4)

In [8]:
arr3

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [9]:
arr4= np.arange(-100,0)
arr4

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81,  -80,  -79,
        -78,  -77,  -76,  -75,  -74,  -73,  -72,  -71,  -70,  -69,  -68,
        -67,  -66,  -65,  -64,  -63,  -62,  -61,  -60,  -59,  -58,  -57,
        -56,  -55,  -54,  -53,  -52,  -51,  -50,  -49,  -48,  -47,  -46,
        -45,  -44,  -43,  -42,  -41,  -40,  -39,  -38,  -37,  -36,  -35,
        -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,  -25,  -24,
        -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,  -13,
        -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,
         -1])

In [10]:
# To Reshape an Array
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Python list
List comprehension
array module(import lib array)
numpy array:
-> zeros
-> Ones
-> full
-> eye
->Arrange
-> Reshape


# Diffrence between list and array
list : we can put diffrent type elements.
Array : we can only put same type of element.
list : Required more time
Array : Required less time
list : It store hetroginious type of data
Array : It store homoginious type of data

In [11]:
lst = list(range(0,10)) 

In [12]:
l2 = [x for x in range(0,10)]
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
l3 = [str(x) for x in range(0,10)] 
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [14]:
l4 = [x**2 for x in range(0,10)]  # To square given list
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [15]:
l5 = [type(x) for x in range(0,10)]
l5

[int, int, int, int, int, int, int, int, int, int]

# To import Array

In [16]:
import array as arr

In [17]:
help(array)

NameError: name 'array' is not defined

In [18]:
a = arr.array('i',l2)
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr1 = arr.array('i',[x**2 for x in l2])
arr1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [20]:
np.array(l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.array([x+3 for x in l2])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
np.array([l2],dtype = float)

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [23]:
# 2-D List
l2d = [[1,2,3],[3,4,5]]
l2d

[[1, 2, 3], [3, 4, 5]]

In [24]:
l3d =[range(i,i+3) for i in [1,3]]
np.array(l3d)

array([[1, 2, 3],
       [3, 4, 5]])

In [25]:
l4d =[range(i,i+3) for i in [1,3,2]]
np.array(l4d)

array([[1, 2, 3],
       [3, 4, 5],
       [2, 3, 4]])

In [26]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [29]:
z = np.zeros((10,10))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
o = np.ones((10,10))
o

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
z[3:7,3:7]=7
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 7., 7., 7., 7., 0., 0., 0.],
       [0., 0., 0., 7., 7., 7., 7., 0., 0., 0.],
       [0., 0., 0., 7., 7., 7., 7., 0., 0., 0.],
       [0., 0., 0., 7., 7., 7., 7., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
z[4:6,4:6]=6
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 7., 7., 7., 7., 0., 0., 0.],
       [0., 0., 0., 7., 6., 6., 7., 0., 0., 0.],
       [0., 0., 0., 7., 6., 6., 7., 0., 0., 0.],
       [0., 0., 0., 7., 7., 7., 7., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
arr8 = np.full((3,3),3.14)
arr8

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

# eye() function for identity matrix

In [34]:
np.eye?

Signature:
np.eye(
    N,
    M=None,
    k=0,
    dtype=<class 'float'>,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference

In [35]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [36]:
np.transpose(np.eye(8))

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [37]:
arr9=np.full((6,6),64)
arr9

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

Linspace - Linearly spaced elements

In [38]:
np.linspace(0,1,5) # starting value,ending value,number of times

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [40]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x000002B0AB4A4400>
File:            c:\users\ayush\appdata\local\programs\python\python312\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting

In [41]:
np.linspace(15,20,20)

array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

Random Function
# btw 0 to 1

In [43]:
np.random?

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\Ayush\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\ayush\appdata\local\programs\python\python312\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============

In [44]:
np.random.random((3,3))

array([[0.09388084, 0.41732292, 0.59026074],
       [0.0788278 , 0.37625516, 0.16846264],
       [0.88735248, 0.78561942, 0.95720917]])

Normal Function - 
value with mean 0 to 1

In [45]:
np.random.normal?

Signature: np.random.normal(loc=0.0, scale=1.0, size=None)
Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width")

In [46]:
np.random.normal(0,1,10)

array([-0.08833174,  0.85033731, -0.74964525,  1.53757545, -1.24362481,
        1.34316308,  0.75116854, -0.03489902, -0.27999112, -0.2032101 ])

In [47]:
np.random.normal(2,2,10)

array([ 2.56982713,  1.29864995,  2.64410607, -0.24017561,  2.11576414,
       -0.68861133,  0.62138076,  2.83263378,  1.63134382, -0.42936498])

Seed Function
in this random values will not change

In [52]:
np.random.seed(5)
np.random.random(10)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
       0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123])

In [53]:
np.random.randn?

Signature: np.random.randn(*args)
Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned 

In [56]:
np.random.randn(2,4)

array([[ 1.85733101, -1.51117956,  0.64484751, -0.98060789],
       [-0.85685315, -0.87187918, -0.42250793,  0.99643983]])

Operation on Numpy

In [58]:
arr1=np.random.randint(0,100,20)
arr1

array([ 9, 38, 47, 16,  5, 34, 45, 59, 24, 13, 31, 32, 76, 44,  5, 14, 47,
       94, 82,  0], dtype=int32)

In [59]:
arr1.ndim  # To check number of dimension

1

In [60]:
arr1.size # To check total number of elements

20

In [61]:
arr1.shape # To check shape

(20,)

In [62]:
arr1.dtype # To check dtype of array

dtype('int32')

Array Indexing

In [64]:
arr=np.random.randint(0,40,10)
arr

array([ 5, 22,  5, 18, 27, 29, 24, 33, 28, 15], dtype=int32)

In [65]:
arr[:4]

array([ 5, 22,  5, 18], dtype=int32)

In [66]:
arr[-5]

np.int32(29)

In [67]:
arr[3]=10

In [68]:
arr

array([ 5, 22,  5, 10, 27, 29, 24, 33, 28, 15], dtype=int32)

In [69]:
arr[2]=9
arr

array([ 5, 22,  9, 10, 27, 29, 24, 33, 28, 15], dtype=int32)

# Numpy Assigments

In [72]:
# Q1
a=np.array([1,2,3])
a

array([1, 2, 3])

In [76]:
b=np.random.randint(1,10,(2,2))
b

array([[7, 4],
       [5, 2]], dtype=int32)

In [77]:
c=np.random.randint(20,30,(3,3))
c

array([[28, 20, 22],
       [22, 24, 21],
       [26, 23, 24]], dtype=int32)

In [78]:
#Q2
c.dtype

dtype('int32')

In [79]:
# Q3
a.shape
a.ndim

1

In [80]:
b.shape
b.ndim

2

In [81]:
c.shape
c.ndim

2

In [83]:
# Q4
d = np.zeros(12)
d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [85]:
# Q5
e = np.ones((2,2))
e

array([[1., 1.],
       [1., 1.]])

In [89]:
# Q6
np.random.seed(10)
math = np.random.randint(0,100,20)
math

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0, 40, 36, 16, 11, 54, 88, 62,
       33, 72, 78], dtype=int32)

In [90]:
# Q12
np.eye(4,4)+5

array([[6., 5., 5., 5.],
       [5., 6., 5., 5.],
       [5., 5., 6., 5.],
       [5., 5., 5., 6.]])

In [91]:
# Q13
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [97]:
# Q18
g=np.arange(0,25).reshape(5,5)
g

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

ValueError: cannot reshape array of size 24 into shape (5,5)